'use server';
/**
 * @fileOverview This file implements a Genkit flow for operational analytics forecasting.
 *
 * - forecastOperationalAnalytics - A function that analyzes sales data and partner performance trends to forecast regional product demand and suggest optimal inventory levels.
 * - OperationalAnalyticsForecastInput - The input type for the forecastOperationalAnalytics function.
 * - OperationalAnalyticsForecastOutput - The return type for the forecastOperationalAnalytics function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const OperationalAnalyticsForecastInputSchema = z.object({
  regionalSalesData: z.array(z.object({
    region: z.string().describe('The geographical region.'),
    productCategory: z.string().describe('The category of the product (e.g., automotive, moto, architectural).'),
    salesVolume: z.number().int().positive().describe('Historical sales volume for the given region and product category.'),
    period: z.string().describe('The time period for which the sales volume is recorded (e.g., "Q1 2023", "Jan 2024").'),
  })).describe('Historical regional sales data.'),
  partnerPerformanceData: z.array(z.object({
    partnerName: z.string().describe('The name of the partner.'),
    region: z.string().describe('The region where the partner operates.'),
    salesVolume: z.number().int().positive().describe('Sales volume generated by this partner.'),
    customerSatisfactionScore: z.number().min(0).max(100).describe('Customer satisfaction score for this partner (0-100).'),
    onTimeDeliveryRate: z.number().min(0).max(100).describe('On-time delivery rate for this partner (0-100).'),
  })).describe('Performance data for partners.'),
  additionalContext: z.string().optional().describe('Any additional context or specific concerns for the forecast.'),
});
export type OperationalAnalyticsForecastInput = z.infer<typeof OperationalAnalyticsForecastInputSchema>;

const OperationalAnalyticsForecastOutputSchema = z.object({
  forecasts: z.array(z.object({
    region: z.string().describe('The geographical region for the forecast.'),
    productCategory: z.string().describe('The product category for the forecast.'),
    predictedDemand: z.number().int().positive().describe('The predicted demand (in units) for the next period.'),
    optimalInventoryLevel: z.number().int().positive().describe('The suggested optimal inventory level (in units) for this region and product category.'),
    reasoning: z.string().describe('Explanation for the predicted demand and optimal inventory level.'),
  })).describe('Detailed regional and product category forecasts with optimal inventory suggestions.'),
  overallSummary: z.string().describe('An overall summary of the forecasting results and key recommendations.'),
});
export type OperationalAnalyticsForecastOutput = z.infer<typeof OperationalAnalyticsForecastOutputSchema>;

export async function forecastOperationalAnalytics(input: OperationalAnalyticsForecastInput): Promise<OperationalAnalyticsForecastOutput> {
  return operationalAnalyticsForecastingFlow(input);
}

const operationalAnalyticsForecastingPrompt = ai.definePrompt({
  name: 'operationalAnalyticsForecastingPrompt',
  input: { schema: OperationalAnalyticsForecastInputSchema },
  output: { schema: OperationalAnalyticsForecastOutputSchema },
  prompt: `You are an expert operations analyst specialized in forecasting regional product demand and suggesting optimal inventory levels.
Your task is to analyze the provided historical sales data and partner performance trends to generate a forecast for regional product demand and suggest optimal inventory levels.

Here is the historical regional sales data:
{{#each regionalSalesData}}
  - Region: {{{region}}}, Product Category: {{{productCategory}}}, Sales Volume: {{{salesVolume}}} units, Period: {{{period}}}
{{/each}}

Here is the partner performance data:
{{#each partnerPerformanceData}}
  - Partner: {{{partnerName}}}, Region: {{{region}}}, Sales Volume: {{{salesVolume}}} units, Customer Sat Score: {{{customerSatisfactionScore}}}%, On-Time Delivery: {{{onTimeDeliveryRate}}}%
{{/each}}

{{#if additionalContext}}
Additional Context: {{{additionalContext}}}
{{/if}}

Based on this data, provide a forecast for regional product demand for the next period and suggest optimal inventory levels. Include a brief reasoning for each forecast and an overall summary of your findings and recommendations.`,
});

const operationalAnalyticsForecastingFlow = ai.defineFlow(
  {
    name: 'operationalAnalyticsForecastingFlow',
    inputSchema: OperationalAnalyticsForecastInputSchema,
    outputSchema: OperationalAnalyticsForecastOutputSchema,
  },
  async (input) => {
    const { output } = await operationalAnalyticsForecastingPrompt(input);
    return output!;
  }
);
